baseURL: "https://evanazevedo.com"
languageCode: "en-us"
title: "Evan Azevedo"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
# theme: novela
module:
  imports:
    - path: "github.com/evanaze/hugo-theme-novela"
paginate: 6
social:
  twitter: "twitter.com/azevedo_evan"
  github: "#evanaze"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors