schema = 3

[mod]
  [mod."github.com/BurntSushi/toml"]
    version = "v0.4.1"
    hash = "sha256-4V42S0+aWqMGyQ/e0UMWWhtOydorIHzILziLSvbA5y8="
  [mod."github.com/PuerkitoBio/goquery"]
    version = "v1.8.0"
    hash = "sha256-I3QaPWATvBOL/F26fIiYWKS13yBUYo+9o3tcsGIu8tY="
  [mod."github.com/abhinav/goldmark-wikilink"]
    version = "v0.3.0"
    hash = "sha256-doMRFPk0qusvhPwVaMuvI5wa1DHTs8ns7S6vnUmNTlI="
  [mod."github.com/adrg/frontmatter"]
    version = "v0.2.0"
    hash = "sha256-WJsVcdCpkIkjqUz5fJOFStZYwQlrcFzQ6+mZatZiimo="
  [mod."github.com/andybalholm/cascadia"]
    version = "v1.3.1"
    hash = "sha256-M0u22DXSeXUaYtl1KoW1qWL46niFpycFkraCEQ/luYA="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.0"
    hash = "sha256-zNSuzjr5n7zhK8VOciSigLMfbnHbmyzsWdTcMlV1kjQ="
  [mod."github.com/jackyzha0/hugo-obsidian"]
    version = "v0.0.0-20230316172945-a7bc6ab3db36"
    hash = "sha256-QBkYMf7LLOilXoGHyEuKhz/UBu1asq49fc/gOE4xTCY="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/stretchr/objx"]
    version = "v0.1.0"
    hash = "sha256-az0Vd4MG3JXfaYbj0Q6AOmNkrXgmXDeQm8+BBiDXmdA="
  [mod."github.com/stretchr/testify"]
    version = "v1.7.0"
    hash = "sha256-t1I9uCrn9vSUu/z5IZuNyGShmbOcJ6UGc2f75ZBrHzE="
  [mod."github.com/yuin/goldmark"]
    version = "v1.4.4"
    hash = "sha256-C/PPf6xFvkG+BhwwiWE9Z0Zt4qKk9gPVNGj+lVxUEY0="
  [mod."golang.org/x/net"]
    version = "v0.0.0-20210916014120-12bc252f5db8"
    hash = "sha256-3Xr6bP9Wi+e3vUHpZ6/Q9ElfXtWjiI2pRWpjPySw1eo="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20210423082822-04245dca01da"
    hash = "sha256-RmbxPPNSEJ71cgwQWXJUh7ZhqGWudgbs/pstc8Z9gHA="
  [mod."golang.org/x/term"]
    version = "v0.0.0-20201126162022-7de9c90e9dd1"
    hash = "sha256-ykpqi1F7Yzo1BVwuG0nbQOZnK0qevcCD2xqbXbsoQq0="
  [mod."golang.org/x/text"]
    version = "v0.3.6"
    hash = "sha256-yP/VW8PvNE6ub82oSu0mnG3VZXMo1PCSbwsWbciQDaw="
  [mod."golang.org/x/tools"]
    version = "v0.0.0-20180917221912-90fa682c2a6e"
    hash = "sha256-NPoE7uVvwjV2PRIxI3DpegOZc8IuUs4XUJuH3ubKHJg="
  [mod."gopkg.in/check.v1"]
    version = "v0.0.0-20161208181325-20d25e280405"
    hash = "sha256-1w5mgYaZUC52uzDnpXXVqle/9AVkH4WePSrQFOVANUw="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.0-20210107192922-496545a6307b"
    hash = "sha256-j8yDji+vqsitpRZirpb4w/Em8nstgf28wpwkcrOlxBk="
